import assert from "node:assert/strict";
import { expansionIntentKey, groupLoadState, materializeGroups, mergeExpansionIntent, mergeGroup, removeExpansionIntent, removeGroup, removeGroupLoadState, setGroupLoadState } from "./flow-state.js";

const root = { node_id: "root" };
const shared = { edge_id: "shared", source_node_id: "root", target_node_id: "table" };
let groups = {};
groups = mergeGroup(groups, "root|W", { nodes: [{ node_id: "table" }], edges: [shared] });
groups = mergeGroup(groups, "root|E", { nodes: [{ node_id: "table" }, { node_id: "extra" }], edges: [shared, { edge_id: "extra", source_node_id: "table", target_node_id: "extra" }] });
assert.deepEqual(materializeGroups(root, groups).edges.find((edge) => edge.edge_id === "shared").owners.sort(), ["root|E", "root|W"]);
assert.deepEqual(materializeGroups(root, groups).nodes.find((node) => node.node_id === "table").loadedBy.sort(), ["root|E", "root|W"]);
const mergedGroups = mergeGroup(groups, "root|R", { nodes: [{ node_id: "table", technical_name: "ORDER_HEADER" }, { node_id: "table", node_type: "TABLE" }], edges: [shared] });
assert.deepEqual(materializeGroups(root, mergedGroups).nodes.find((node) => node.node_id === "table"), { node_id: "table", technical_name: "ORDER_HEADER", node_type: "TABLE", loadedBy: ["root|W", "root|E", "root|R"] });
groups = removeGroup(groups, "root|W");
assert.deepEqual(materializeGroups(root, groups).edges.map((edge) => edge.edge_id).sort(), ["extra", "shared"]);
groups = removeGroup(groups, "root|E");
assert.deepEqual(materializeGroups(root, groups), { nodes: [{ ...root, loadedBy: ["root"] }], edges: [] });
let states = {};
states = setGroupLoadState(states, "root|E", { loading: true });
assert.equal(groupLoadState(states, "root|E").loading, true);
states = setGroupLoadState(states, "root|E", { loading: false, truncated: true });
assert.equal(groupLoadState(states, "root|E").truncated, true);
states = removeGroupLoadState(states, "root|E");
assert.deepEqual(groupLoadState(states, "root|E"), { loading: false, error: "", truncated: false });
let intents = {};
intents = mergeExpansionIntent(intents, root, "E", "out");
assert.equal(expansionIntentKey("root", "E", "out"), "root|out|E");
assert.deepEqual(Object.keys(intents), ["root|out|E"]);
intents = removeExpansionIntent(intents, "root", "E", "out");
assert.deepEqual(intents, {});
console.log("flow-state self-check passed");
