import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const read = (relativePath) => readFileSync(resolve(here, relativePath), "utf8");
const count = (text, needle) => (text.match(new RegExp(needle.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "g")) || []).length;

const app = read("CodeFlowApp.jsx");
const main = read("main.jsx");
const apiModule = read("code-flow/api.js");
const constants = read("code-flow/constants.js");
const detailPanel = read("code-flow/DetailPanel.jsx");
const detailTabs = read("code-flow/detail-tabs.jsx");
const detailUi = read("code-flow/detail-ui.jsx");
const flowNode = read("code-flow/FlowNode.jsx");
const format = read("code-flow/format.js");
const layout = read("code-flow/layout.js");
const pathUtils = read("code-flow/path-utils.js");
const styles = read("styles.css");
const source = [app, apiModule, constants, detailPanel, detailTabs, detailUi, flowNode, format, layout, pathUtils, styles].join("\n");

assert.doesNotMatch(main, /VITE_CODE_FLOW_GRAPH|function App\(|\/api\/schemas|schema/i);
assert.match(main, /<CodeFlowApp\s*\/?\s*>/);
assert.doesNotMatch(source, /schema/i);

assert.match(constants, /export const modes\s*=\s*\["1",\s*"W",\s*"R",\s*"E"\]/);
assert.match(constants, /export const modeLabels\s*=\s*\{/);
assert.doesNotMatch(constants, /modeDescriptions/);
assert.doesNotMatch(constants, /modeOptions/);
assert.match(constants, /"1":\s*"[^"]+"/);
assert.match(constants, /W:\s*"[^"]+"/);
assert.match(constants, /R:\s*"[^"]+"/);
assert.match(constants, /E:\s*"[^"]+"/);
assert.match(constants, /export const DEFAULT_DETAIL_WIDTH\s*=\s*500/);
assert.match(apiModule, /export const EVIDENCE_PAGE_SIZE\s*=/);
assert.match(apiModule, /export const emptyEvidencePage\s*=/);
assert.match(constants, /export const DETAIL_WIDTH_STORAGE_KEY\s*=\s*"code-flow-detail-width"/);

assert.match(flowNode, /export function FlowNode\(\{ data \}\)/);
assert.match(flowNode, /export const nodeTypes\s*=\s*\{ flowNode: FlowNode \}/);
assert.match(flowNode, /export function NodeFlowControls\(\{ node, direction, data \}\)/);
assert.match(flowNode, /node-flow-controls nodrag/);
assert.match(flowNode, /<NodeFlowControls node=\{node\} direction="in" data=\{data\} \/>/);
assert.match(flowNode, /<NodeFlowControls node=\{node\} direction="out" data=\{data\} \/>/);
assert.match(flowNode, /Boolean\(data\.intents\?\.\[expansionIntentKey\(node\.node_id, mode, direction\)\] \|\| data\.groups\?\.\[key\]\)/);
assert.match(flowNode, /className=\{\[active \? "active" : "", state\.loading \? "loading" : "", state\.error \? "error" : "", state\.truncated \? "truncated" : ""\]/);
assert.equal(count(flowNode, "modes.map"), 1);
assert.equal(count(detailUi, "modes.map"), 0);
assert.equal(count(app, "modes.map"), 0);
assert.equal(count(source, "modes.map"), 1);

assert.doesNotMatch(detailUi, /ExpansionControls/);
assert.doesNotMatch(detailUi, /groupLoadState|expansionIntentKey|modeDescriptions|className="detail-expansion"|className="detail-expand-row"|className="mode-legend"|className="mode-legend-item"|onToggle\(node, mode, direction/);
assert.match(detailUi, /export function DetailLinkButton\(\{ children, onClick, title \}\)/);
assert.match(detailUi, /className="detail-link-button"/);

assert.doesNotMatch(detailPanel, /ExpansionControls/);
assert.doesNotMatch(detailPanel, /groups = \{\}|loadStates = \{\}|intents = \{\}|onToggleFlow|semantic, filters|groups=\{groups\}|loadStates=\{loadStates\}|intents=\{intents\}/);
assert.doesNotMatch(app, /groups=\{groups\}|loadStates=\{groupStates\}|intents=\{expansionIntents\}|onToggleFlow=\{toggleNodeFlow\}|semantic=\{semantic\}|filters=\{filtersKey\}/);
assert.match(app, /type:\s*"flowNode"/);
assert.match(app, /onToggleFlow:\s*stableToggleNodeFlow/);
assert.doesNotMatch(app, /Root expansion/);
assert.doesNotMatch(app, /checked=\{active\}/);
assert.doesNotMatch(app, /expansionIntentKey\(root\.node_id, mode, "both"\)/);
assert.match(detailPanel, /onSelectNode=\{onSelectNode\}/);
assert.match(detailPanel, /canGoBack \? <button type="button" className="detail-back" onClick=\{onBack\}/);
assert.match(detailPanel, /node\.node_type === "TABLE"/);
assert.match(detailPanel, /<BusinessSemantic node=\{node\} selected=\{detail\?\.business_semantics \|\| \[\]\}/);
assert.match(detailPanel, /<ColumnsTab columns=\{detail\?\.columns \|\| \[\]\}/);
assert.match(detailPanel, /<NodeOverview node=\{node\} nodes=\{detail\?\.semantic_tree_nodes \|\| \{\}\} businessSemantics=\{detail\?\.semantic_tree_business_semantics \|\| \{\}\} localized=\{localized\} onSelectNode=\{onSelectNode\}/);
assert.doesNotMatch(detailPanel, /Incoming W\/R flows|FlowTab|RelationsTab|EdgeOverview|TabBar|onSelectEdge|evidence|knowledge/i);
assert.match(detailTabs, /export function BusinessSemantic\(\{ node, selected = \[\] \}\)/);
assert.match(detailTabs, /\/business-semantic-suggestions\?target_id=/);
assert.match(detailTabs, /method: "PUT"/);
assert.match(detailTabs, /Nhập tên người xác nhận/);
assert.doesNotMatch(detailTabs, /X-Code-Map-Token|Editor token|type="password"/);
assert.match(detailTabs, /onClick=\{\(\) => setEditing\(true\)\}/);
assert.match(detailTabs, /Click để đổi/);
assert.match(detailTabs, /<details className="business-semantic-picker"/);
assert.match(detailTabs, /semanticTree\?\.children\?\.length/);
assert.match(detailTabs, /function SemanticInfo\(\{ semantic \}\)/);
assert.match(detailTabs, /<details className="semantic-tree-info">/);
assert.match(detailTabs, /className="semantic-tree-popover" role="tooltip"/);
assert.match(styles, /\.detail-subcard \.semantic-tree-info \{[^}]*overflow: visible/);
assert.match(styles, /\.detail-subcard \.semantic-tree-info summary \{[^}]*padding: 0/);
assert.match(detailTabs, /Xác nhận bởi \{semantic\.author_name\}/);
assert.match(detailTabs, /function SemanticBranch\(\{ item, nodes, businessSemantics, localized, onSelectNode \}\)/);
assert.match(detailTabs, /businessSemantics\[item\.ref_node_id\]/);
assert.match(detailTabs, /nodes\[item\.ref_node_id\]/);
assert.match(detailTabs, /businessSemantics\[node\.node_id\]/);
assert.match(detailTabs, /<h4>Semantic tree<\/h4>/);
assert.match(detailTabs, /const names = bilingualNames\(column, localized\)/);
assert.match(detailTabs, /names\.ja \|\| "—"/);
assert.match(detailTabs, /names\.en \|\| "—"/);
assert.match(detailTabs, /Related table/);
assert.match(detailTabs, /p\.relation_table \|\| "—"/);
assert.match(detailUi, /export function EntityIdentity\(\{ node, localized, compact = false \}\)/);
assert.match(detailUi, /identityText\(node, localized\)/);
assert.match(flowNode, /<small>Mã:<\/small>/);
assert.match(flowNode, /<small>JA:<\/small>/);
assert.match(flowNode, /<small>EN:<\/small>/);

assert.match(apiModule, /\/api\/graph\$\{path\}/);
assert.match(app, /\/search\?q=\$\{encodedTerm\}&exclude_node_types=COLUMN&locale=ja&limit=40/);
assert.match(app, /const term = query\.trim\(\)/);
assert.match(app, /\}, \[query\]\);/);
assert.match(app, /function abortSearch\(\)/);
assert.match(app, /searchRequest\.current\.abort\(\)/);
assert.match(app, /prioritizeSearchResults\(term, Array\.isArray\(rows\) \? rows : \[\]\)/);
assert.match(app, /const \[searchOpen, setSearchOpen\] = useState\(false\)/);
assert.match(app, /const \[browseResults, setBrowseResults\] = useState\(\[\]\)/);
assert.match(app, /function loadBrowseRoots\(\)/);
assert.match(app, /\/search\?q=&exclude_node_types=COLUMN&limit=40/);
assert.match(app, /className="code-flow-search-browse"/);
assert.match(app, /className="root-list"/);
assert.doesNotMatch(app, /code-flow-results/);
assert.match(app, /className="empty-search"/);
assert.match(format, /left\.localized_display_name/);
assert.match(format, /export function localizedName\(node, localized = \{\}, language = "en"\)/);
assert.match(format, /export function displayName\(node, localized = \{\}\)/);
assert.match(format, /export function bilingualNames\(node, localized = \{\}\)/);
assert.match(format, /export function identityParts\(node, localized = \{\}\)/);
assert.match(format, /export function identityText\(node, localized = \{\}\)/);
assert.match(format, /\[ja, en\]\.filter\(Boolean\)\.join\(" - "\)/);
assert.doesNotMatch(format, /Not registered/);
assert.match(format, /friendlyDisplayText\(value, node\.node_id\)/);
assert.match(format, /export function humanizeInternalId\(value = ""\)/);
assert.match(format, /export function localizedDescription\(node, localized = \{\}, language = "en"\)/);
assert.match(format, /export function collectLocalizationIds\(\.\.\.values\)/);
assert.match(app, /collectLocalizationIds\(graph\.nodes, results, browseResults, selected, detail\)/);
assert.match(app, /\[graph\.nodes, results, browseResults, selected, detail\]/);
assert.match(app, /\/localization\?\$\{localizationIds\.map/);
assert.doesNotMatch(app, /\[locale, setLocale\]|code-flow-locale|encodeURIComponent\(locale\)|<option value="ja">/);
assert.match(app, /<EntityIdentity node=\{node\} localized=\{localized\} compact \/>/);

assert.doesNotMatch(app, /loadEvidence|selectEdgeById|\/knowledge\?target_id|EVIDENCE_PAGE_SIZE|emptyEvidencePage/);
assert.match(app, /const \[detailHistory, setDetailHistory\] = useState\(\[\]\)/);
assert.match(app, /function selectNodeById\(nodeId\)/);
assert.match(app, /setDetailHistory\(\(current\) => \[\.\.\.current, selected\]\)/);
assert.match(app, /function backDetail\(\)/);
assert.match(app, /setDetailHistory\(\(current\) => current\.slice\(0, -1\)\)/);
assert.match(app, /canGoBack=\{detailHistory\.length > 0\}/);
assert.match(app, /onBack=\{backDetail\}/);
assert.match(app, /`\/detail\?target_id=\$\{encodeURIComponent\(targetId\)\}&target_type=\$\{targetType\}&locale=vi`/);

assert.match(constants, /export const flowKey = \(nodeId, mode, direction = "both", semanticLevel = "TECHNICAL", filters = ""\) => `\$\{nodeId\}\|\$\{direction\}\|\$\{mode\}\|\$\{semanticLevel\}\|\$\{filters\}`/);
assert.match(app, /function refreshExpandedGraph\(\s*nextSemantic = semantic,\s*nextMaxNodes = maxNodes,?\s*\)/);
assert.match(app, /function handleSemanticChange\(nextSemantic\)/);
assert.match(app, /setSemantic\(nextSemantic\);\s*refreshExpandedGraph\(nextSemantic, maxNodes\);/);
assert.match(app, /function loadFlowGroup\(\s*node,\s*mode,\s*direction = "both",\s*semanticLevel = semantic,\s*maxNodeValue = maxNodes,?\s*\)/);
assert.match(app, /const controller = new AbortController\(\)/);
assert.match(app, /abortExpansion\(key\)/);
assert.match(app, /setGroupLoadState\(current, key, \{\s*loading: true,\s*error: "",\s*truncated: false,?\s*\}\)/);
assert.match(app, /\/flow\?node_id=\$\{encodeURIComponent\(node\.node_id\)\}&mode=\$\{mode\}&direction=\$\{direction\}&max_nodes=\$\{maxNodeValue\}&semantic_level=\$\{semanticLevel\}/);
assert.match(app, /\$\{directionLabels\[direction\]\} \$\{mode\}: \$\{\(data\.nodes \|\| \[\]\)\.length\} nodes, \$\{\(data\.edges \|\| \[\]\)\.length\} edges/);

assert.match(layout, /export function buildAutoLayout\(nodes, edges, anchorId, localized = \{\}\)/);
assert.match(app, /buildAutoLayout\(\s*visibleNodes,\s*visibleEdges,\s*root\?\.node_id \|\| selectedNodeId,\s*localized,?\s*\)/);
assert.match(app, /position: manualNodePositions\[node\.node_id\] \|\| node\.position/);
assert.match(app, /data-layout="auto-layered"/);
assert.match(app, /const \[layoutNonce, setLayoutNonce\] = useState\(0\)/);
assert.match(app, /const \[manualNodePositions, setManualNodePositions\] = useState\(\{\}\)/);
assert.match(app, /function runAutoLayout\(\)/);
assert.match(app, /function handleNodesChange\(changes\)/);
assert.match(app, /change\.type === "position" &&\s*change\.position &&\s*change\.dragging === false/);
assert.match(app, /<Controls showInteractive=\{false\}>/);
assert.match(app, /className="react-flow__controls-button code-flow-auto-layout-control"/);
assert.match(app, /disabled=\{!flowNodes\.length\}/);
assert.match(app, /onClick=\{runAutoLayout\}/);
assert.match(app, /<LayoutGrid size=\{16\} aria-hidden="true" \/>/);
assert.match(app, /onInit=\{\(instance\) => \{\s*flowInstance\.current = instance;\s*\}\}/);
assert.match(app, /nodesDraggable[\s\S]*onNodesChange=\{handleNodesChange\}/);
assert.match(app, /fitView\?\.\(\{ padding: 0\.18, duration: 220 \}\)/);
assert.doesNotMatch(app, /position:\s*\{\s*x:\s*\(index % 4\) \* 300,\s*y:\s*Math\.floor\(index \/ 4\) \* 170\s*\}/);
assert.match(app, /type:\s*"flowNode"/);
assert.match(app, /onNodeClick=\{\(_, node\) =>/);
assert.doesNotMatch(app, /onEdgeClick/);
assert.doesNotMatch(app, /incomingFlows|activeFlow|setActiveFlow|direction=in/);
assert.doesNotMatch(detailPanel, /Incoming W\/R flows/);
assert.doesNotMatch(styles, /incoming-flow-list|code-flow-dimmed|code-flow-path-node/);
assert.match(app, /nodeTypes=\{nodeTypes\}/);
assert.match(app, /const \[detailWidth, setDetailWidth\] = useState\(\(\) => \{/);
assert.match(app, /window\.localStorage\.getItem\(DETAIL_WIDTH_STORAGE_KEY\)/);
assert.match(app, /window\.localStorage\.setItem\(\s*DETAIL_WIDTH_STORAGE_KEY/);
assert.match(app, /function startDetailResize\(event\)/);
assert.match(app, /function resizeDetailWithKeyboard\(event\)/);
assert.match(app, /className="detail-resizer"[\s\S]*role="separator"/);
assert.match(app, /aria-orientation="vertical"/);
assert.doesNotMatch(app, /GraphLegend|code-flow-graph-legend|legend-swatch|legend-node/);
assert.doesNotMatch(app, /<h4>Expansion mode legend<\/h4>/);
assert.doesNotMatch(app, /<h4>Expansion modes<\/h4>/);
assert.doesNotMatch(app, /modeDescriptions\[mode\]/);
assert.doesNotMatch(app, /modes\.map/);
assert.doesNotMatch(app, /className="mode-legend"|className="mode-legend-item"/);
assert.match(styles, /\.code-flow-search-browse/);
assert.match(styles, /\.code-flow-toolbar > span\[role="status"\]/);
assert.doesNotMatch(styles, /code-flow-graph-legend|legend-swatch|legend-node/);
assert.match(styles, /\.detail-resizer/);
assert.doesNotMatch(styles, /^\*,\s*\.evidence-list\s*\{/m);
assert.match(styles, /\.evidence-list\s*\{\s*display:\s*grid;\s*gap:\s*7px;/);
assert.doesNotMatch(styles, /\.detail-expansion/);
assert.doesNotMatch(styles, /\.detail-expand-row/);
assert.doesNotMatch(styles, /\.mode-legend/);
assert.doesNotMatch(styles, /\.mode-legend-item/);
assert.ok(!styles.includes(".debug-metadata"));
assert.ok(!styles.includes(".detail-json"));
assert.match(styles, /\.node-flow-controls/);
assert.match(styles, /\.source-list/);
assert.match(styles, /\.source-snippet/);

console.log("graph-ui contract self-check passed");
