CREATE OR REPLACE TRIGGER TRG_SHIPMENT_AUDIT
AFTER UPDATE OF STATUS ON SHIPMENT
FOR EACH ROW
WHEN (OLD.STATUS <> NEW.STATUS)
BEGIN
	INSERT INTO SHIPMENT_AUDIT (
		AUDIT_ID,
		SHIPMENT_ID,
		STATUS
	) VALUES (
		SHIPMENT_AUDIT_SEQ.NEXTVAL,
		:NEW.SHIPMENT_ID,
		:NEW.STATUS
	);
	-- Shipment status change inserts audit row
END;
/
-- end trigger fixture

CREATE OR REPLACE PACKAGE BODY PKG_ORDER AS

	PROCEDURE CREATE_ORDER(
		p_customer_id IN NUMBER,
		p_request_key IN VARCHAR2
	) IS
		v_order_id NUMBER;
		v_total NUMBER;
	BEGIN
		v_order_id := ORDER_SEQ.NEXTVAL;
		VALIDATE_LINES(p_customer_id);
		v_total := CALCULATE_TOTAL(p_customer_id);
		INSERT INTO ORDER_HEADER (
			ORDER_ID, CUSTOMER_ID, STATUS, TOTAL_AMOUNT, CREATED_AT
		) VALUES (
			v_order_id, p_customer_id, 'PENDING', v_total, SYSTIMESTAMP
		);
		INSERT INTO ORDER_LINE (
			ORDER_LINE_ID, ORDER_ID, PRODUCT_ID, QUANTITY, UNIT_PRICE
		) SELECT ORDER_LINE_SEQ.NEXTVAL, v_order_id, PRODUCT_ID, QUANTITY, UNIT_PRICE
				FROM ORDER_STAGING_LINES
			 WHERE CUSTOMER_ID = p_customer_id;
		INSERT INTO INVENTORY_RESERVATION (
			RESERVATION_ID, ORDER_ID, PRODUCT_ID, QUANTITY, STATUS
		) SELECT RESERVATION_SEQ.NEXTVAL, v_order_id, PRODUCT_ID, QUANTITY, 'RESERVED'
				FROM ORDER_LINE
			 WHERE ORDER_ID = v_order_id;
		INSERT INTO PAYMENT_TRANSACTION (
			PAYMENT_ID, ORDER_ID, STATUS, AMOUNT
		) VALUES (
			PAYMENT_SEQ.NEXTVAL, v_order_id, 'PENDING', v_total
		);
	EXCEPTION
		WHEN DUP_VAL_ON_INDEX THEN
			INSERT INTO PAYMENT_TRANSACTION (
				PAYMENT_ID, ORDER_ID, STATUS, AMOUNT
			) VALUES (
				PAYMENT_SEQ.NEXTVAL, v_order_id, 'FAILED', 0
			);
			RAISE;
	END CREATE_ORDER;

	PROCEDURE VALIDATE_LINES(p_customer_id IN NUMBER) IS
	BEGIN
		NULL;
	END VALIDATE_LINES;

	FUNCTION CALCULATE_TOTAL(p_customer_id IN NUMBER)
		RETURN NUMBER
	IS
		v_rate NUMBER;
		v_total NUMBER;
	BEGIN
		SELECT SUM(QUANTITY * UNIT_PRICE)
			INTO v_total
			FROM ORDER_STAGING_LINES
		 WHERE CUSTOMER_ID = p_customer_id;
		SELECT rate FROM TAX_SCHEMA.TAX_RATE@TAX_DB_LINK INTO v_rate;
		RETURN v_total * v_rate;
	END CALCULATE_TOTAL;

	PROCEDURE APPLY_TAX_API(p_order_id IN NUMBER) IS
	BEGIN
		NULL; -- external-api:TAX_SYSTEM:POST:/tax/calculate
	END APPLY_TAX_API;

	PROCEDURE CANCEL_ORDER(p_order_id IN NUMBER)
	IS
		v_status VARCHAR2(20) := 'CANCELLED';
	BEGIN
		UPDATE ORDER_HEADER
			 SET STATUS = v_status
		 WHERE ORDER_ID = p_order_id;
		DELETE FROM INVENTORY_RESERVATION
		 WHERE ORDER_ID = p_order_id;
		INSERT INTO SHIPMENT_AUDIT (
			AUDIT_ID,
			SHIPMENT_ID,
			STATUS
		) SELECT SHIPMENT_AUDIT_SEQ.NEXTVAL,
						 SHIPMENT_ID,
						 'CANCELLED'
				FROM SHIPMENT
			 WHERE ORDER_ID = p_order_id;
		-- CANCEL_ORDER releases reservations
		IF SQL%ROWCOUNT = 0 THEN
			NULL;
		END IF;

		-- Column write fixture follows exact snippet from package evidence.
		UPDATE ORDER_HEADER SET STATUS = :status WHERE ORDER_ID = :order_id;
	END CANCEL_ORDER; -- UPDATE ORDER_HEADER SET STATUS = :status

	PROCEDURE ALLOCATE_ORDER(p_order_id IN NUMBER)
	IS
		v_stock NUMBER;
		v_sql VARCHAR2(4000);
	BEGIN
		SELECT COUNT(*)
			INTO v_stock
			FROM ORDER_HEADER
		 WHERE ORDER_ID = p_order_id;
		IF v_stock > 0 THEN
			INSERT INTO FULFILLMENT_ALLOCATION
				(ALLOCATION_ID, ORDER_ID, STATUS)
			VALUES (FULFILLMENT_SEQ.NEXTVAL, p_order_id, 'ALLOCATED');
			UPDATE ORDER_HEADER
				 SET STATUS = 'ALLOCATED'
			 WHERE ORDER_ID = p_order_id;
		ELSE
			-- Insufficient stock creates BACKORDER
			INSERT INTO BACKORDER (
				BACKORDER_ID,
				ORDER_ID,
				QUANTITY
			) VALUES (
				BACKORDER_SEQ.NEXTVAL, p_order_id, 1
			);
		END IF;
		v_sql := 'UPDATE ORDER_HEADER SET STATUS = ''ALLOCATED'' WHERE ORDER_ID = :id';
		EXECUTE IMMEDIATE v_sql;
		-- Runtime SQL target cannot be resolved
		INSERT INTO SHIPMENT
			(SHIPMENT_ID, ORDER_ID, STATUS)
		VALUES (SHIPMENT_SEQ.NEXTVAL, p_order_id, 'CREATED');
		INSERT INTO SHIPMENT_PACKAGE
			(PACKAGE_ID, SHIPMENT_ID)
		SELECT PACKAGE_SEQ.NEXTVAL, SHIPMENT_ID
			FROM SHIPMENT
		 WHERE ORDER_ID = p_order_id;
		-- ALLOCATE_ORDER creates allocation or backorder
		NULL;
	END ALLOCATE_ORDER;

END PKG_ORDER;
/
