LOAD DATA
INFILE 'orders.csv'
BADFILE 'orders.bad'
DISCARDFILE 'orders.discard'
APPEND
INTO TABLE ORDER_HEADER
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
(
  ORDER_ID INTEGER EXTERNAL,
  CUSTOMER_ID INTEGER EXTERNAL,
  STATUS CHAR,
  TOTAL_AMOUNT DECIMAL EXTERNAL,
  CREATED_AT TIMESTAMP "YYYY-MM-DD HH24:MI:SS"
)
