-- Invalid source configuration fixture: missing database mapping

WITH source_orders AS (
	SELECT oh.ORDER_ID,
				 oh.STATUS,
				 sp.SHIPMENT_ID
		FROM ORDER_HEADER oh
		LEFT JOIN SHIPMENT sp
			ON sp.ORDER_ID = oh.ORDER_ID
	 WHERE oh.CREATED_AT >= TRUNC(SYSDATE) - 1
),
open_shipments AS (
	SELECT SHIPMENT_ID FROM SHIPMENT WHERE STATUS <> 'CLOSED'
)

MERGE INTO ORDER_DAILY_SUMMARY dst
USING (
	SELECT TRUNC(SYSDATE) AS SUMMARY_DATE,
				 COUNT(*) AS ORDER_COUNT,
				 SUM(oh.TOTAL_AMOUNT) AS TOTAL_AMOUNT
		FROM ORDER_HEADER oh
		JOIN source_orders so
			ON so.ORDER_ID = oh.ORDER_ID
	 GROUP BY TRUNC(SYSDATE)
) src
ON (dst.SUMMARY_DATE = src.SUMMARY_DATE)
WHEN MATCHED THEN UPDATE SET dst.ORDER_COUNT = src.ORDER_COUNT,
														 dst.TOTAL_AMOUNT = src.TOTAL_AMOUNT
WHEN NOT MATCHED THEN INSERT (SUMMARY_DATE, ORDER_COUNT, TOTAL_AMOUNT)
VALUES (src.SUMMARY_DATE, src.ORDER_COUNT, src.TOTAL_AMOUNT);
SELECT FROM WHERE MALFORMED;
